services:
  postgres:
    image: postgres:17-alpine
    container_name: xo-game-postgres
    env_file:
      - ./api/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data:
